### ISSUE TITLE
Erro SDK version

### ISSUE THREAD

**Issue by GamingTechEdu** [israelagoeiro/coocree_radio_group#3]
Estou tendo um erro com a versão do SDK, ao tentar fazer um pub get ou pub upgrade tenho a seguinte mensagem:

The current Dart SDK version is 2.18.6.

Because example requires SDK version >=2.19.0 <3.0.0, version solving failed.
pub finished with exit code 1

isso afeta o código inteiro assim não consigo rodar testes.

**Comment by israelagoeiro** [comment]
Antes de colocar uma issue precisa verificar o que o erro signica no google e tentar descobrir se não consegue você mesmo resolver o problema. Esse é um problema bem simples de resolver.

Achei a resposta no google.
https://stackoverflow.com/questions/56351254/flutter-requires-sdk-version
